## Data Analytics 2 Logistic Regression

Import required libraries

In [1]:
import pandas as pd 
import numpy as np 

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [6]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [7]:
# Check null values
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

split dataset into features and output

In [8]:
df_y = df['Purchased']

In [9]:
df_x = df.drop('Purchased',axis=1)

In [10]:
print(df_y.describe(), end = "\n\n")
print(df_x.describe())

count    400.000000
mean       0.357500
std        0.479864
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: Purchased, dtype: float64

            User ID         Age  EstimatedSalary
count  4.000000e+02  400.000000       400.000000
mean   1.569154e+07   37.655000     69742.500000
std    7.165832e+04   10.482877     34096.960282
min    1.556669e+07   18.000000     15000.000000
25%    1.562676e+07   29.750000     43000.000000
50%    1.569434e+07   37.000000     70000.000000
75%    1.575036e+07   46.000000     88000.000000
max    1.581524e+07   60.000000    150000.000000


In [11]:
df_y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
df_x

User ID  Gender  Age  EstimatedSalary
0    15624510    Male   19            19000
1    15810944    Male   35            20000
2    15668575  Female   26            43000
3    15603246  Female   27            57000
4    15804002    Male   19            76000
..        ...     ...  ...              ...
395  15691863  Female   46            41000
396  15706071    Male   51            23000
397  15654296  Female   50            20000
398  15755018    Male   36            33000
399  15594041  Female   49            36000

[400 rows x 4 columns]

Split into train and test data

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.3, random_state = 48)

In [14]:
print(x_train,"\n\n\n\n",x_test)

      User ID  Gender  Age  EstimatedSalary
132  15725660    Male   30            87000
372  15629885  Female   39            73000
56   15775562  Female   23            48000
141  15666141  Female   18            68000
333  15587177    Male   40            65000
..        ...     ...  ...              ...
320  15774872  Female   52           138000
347  15768151  Female   54           108000
337  15612465    Male   35            79000
51   15764195  Female   18            44000
0    15624510    Male   19            19000

[280 rows x 4 columns] 



       User ID  Gender  Age  EstimatedSalary
150  15679651  Female   26            15000
206  15654230  Female   55           130000
191  15662067  Female   19            26000
243  15769596  Female   56           104000
385  15775335    Male   56            60000
..        ...     ...  ...              ...
110  15665416  Female   39            71000
87   15631912  Female   28            85000
335  15601550  Female   36            54000
259

In [15]:
print(y_train,"\n\n\n\n",y_test)

132    0
372    0
56     0
141    0
333    0
      ..
320    1
347    1
337    0
51     0
0      0
Name: Purchased, Length: 280, dtype: int64 



 150    0
206    1
191    0
243    1
385    1
      ..
110    0
87     0
335    0
259    1
38     0
Name: Purchased, Length: 120, dtype: int64


In [17]:
x_train.shape

(280, 4)

In [18]:
x_test.shape

(120, 4)

In [19]:
y_test.shape

(120,)

In [20]:
y_train.shape

(280,)

Converting categorical data to numeric data

In [26]:
gender = pd.get_dummies(x_train['Gender'])
gender['Male']

132    1
372    0
56     0
141    0
333    1
      ..
320    0
347    0
337    1
51     0
0      1
Name: Male, Length: 280, dtype: uint8

In [27]:
x_train['Gender'] = gender['Male']

<ipython-input-27-b59b70abb293>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train['Gender'] = gender['Male']


In [28]:
x_train

User ID  Gender  Age  EstimatedSalary
132  15725660       1   30            87000
372  15629885       0   39            73000
56   15775562       0   23            48000
141  15666141       0   18            68000
333  15587177       1   40            65000
..        ...     ...  ...              ...
320  15774872       0   52           138000
347  15768151       0   54           108000
337  15612465       1   35            79000
51   15764195       0   18            44000
0    15624510       1   19            19000

[280 rows x 4 columns]

In [29]:
gender = pd.get_dummies(x_test['Gender'])
x_test['Gender'] = gender['Male']

<ipython-input-29-75d9be58ea18>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test['Gender'] = gender['Male']


In [30]:
x_test

User ID  Gender  Age  EstimatedSalary
150  15679651       0   26            15000
206  15654230       0   55           130000
191  15662067       0   19            26000
243  15769596       0   56           104000
385  15775335       1   56            60000
..        ...     ...  ...              ...
110  15665416       0   39            71000
87   15631912       0   28            85000
335  15601550       0   36            54000
259  15815236       0   45           131000
38   15671766       0   26            72000

[120 rows x 4 columns]

Standardizing the data

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [32]:
x_train

array([[ 0.45961027,  1.        , -0.717493  ,  0.53779252],
       [-0.86967632, -1.        ,  0.13097362,  0.12312952],
       [ 1.15221335, -1.        , -1.37741149, -0.61734011],
       ...,
       [-1.11145312,  1.        , -0.24612266,  0.30084223],
       [ 0.99444774, -1.        , -1.84878183, -0.73581525],
       [-0.94427737,  1.        , -1.75450776, -1.47628489]])

In [33]:
x_test

array([[-0.13559682, -0.93541435, -1.15952191, -1.64115117],
       [-0.49680755, -0.93541435,  1.70024863,  1.6791664 ],
       [-0.38545046, -0.93541435, -1.84981135, -1.32355558],
       [ 1.1424449 , -0.93541435,  1.79886141,  0.92848591],
       [ 1.2239912 ,  1.06904497,  1.79886141, -0.34189647],
       [ 1.49859717, -0.93541435, -1.15952191,  1.33269848],
       [ 1.38964143, -0.93541435, -0.86368357,  0.32216705],
       [-1.12998135, -0.93541435,  2.09469974,  0.46652868],
       [-1.44613487, -0.93541435,  0.41828253,  0.52427333],
       [ 0.79413608,  1.06904497, -1.15952191,  0.23555007],
       [ 0.07238246, -0.93541435, -0.56784524,  1.30382616],
       [ 0.91886397, -0.93541435,  1.10857197,  1.996762  ],
       [ 1.73327544, -0.93541435, -0.27200691,  0.14893309],
       [-0.84480377, -0.93541435,  0.91134642, -0.60174741],
       [ 0.05783229,  1.06904497,  0.02383142, -0.60174741],
       [-0.2213064 ,  1.06904497, -1.25813468,  0.43765635],
       [ 1.19716433,  1.

INITIALIZING MODEL

In [34]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression(random_state = 0)


In [35]:
logistic.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [36]:
y_pred = logistic.predict(x_test)

In [37]:
y_pred

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [38]:
y_test

150    0
206    1
191    0
243    1
385    1
      ..
110    0
87     0
335    0
259    1
38     0
Name: Purchased, Length: 120, dtype: int64

In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [40]:
cm

array([[75,  3],
       [13, 29]], dtype=int64)

In [41]:
# accuracy score
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,y_pred)

In [42]:
score

0.8666666666666667

In [43]:
(75 + 29)/(75 + 3 +13+29)

0.8666666666666667

In [45]:
# true positive
tp = cm[0,[0]]
tp

array([75], dtype=int64)

In [50]:
tn = cm[1,[1]]
tn

array([29], dtype=int64)

In [52]:
fp = cm[0,[0]]
fp

array([3], dtype=int64)

In [53]:
fn = cm[1,[0]]
fn

array([13], dtype=int64)

In [54]:
accuracy_cm = ((tp + tn)/(tp + fp + fn + tn))
print('Accuracy : ',accuracy_cm*100)

Accuracy :  [86.66666667]


In [55]:
error_rate_cm = ((fp + fn)/(tp + fp + fn + tn))
print('Error Rate : ', error_rate_cm*100)

Error Rate :  [13.33333333]


In [56]:
precision_cm = (tp / (tp + fp))
print('Precision : ',precision_cm*100)

Precision :  [96.15384615]


In [57]:
#recall is also called sensitivity
recall_cm = (tp / (tp + fn))
print('Sensitivity : ', recall_cm*100)

Sensitivity :  [85.22727273]


In [58]:
specificity_cm = (tn / (tn + fp))
print('Specificity : ', specificity_cm*100)

Specificity :  [90.625]


In [59]:
from sklearn.metrics import precision_score, recall_score
precision_score(y_test,y_pred)

0.90625

In [60]:
recall_score(y_test,y_pred)

0.6904761904761905